const fs = require('fs');
const path = require('path');
const ejs = require('ejs');
const { buildPythonFiles } = require('./pythonBuilder');
const { buildCsharpFiles } = require('./csharpBuilder');
const { buildJavaFiles }   = require('./javaBuilder');

// ─── EJS Templates (Node.js / Express) ───────────────────────────────────────

const TEMPLATES = {
  appJs: `const express = require('express');
const app = express();
const port = process.env.PORT || 3000;

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Routes
<%- routes %>

app.listen(port, () => {
  console.log('<%= projectName %> is running on port ' + port);
});

module.exports = app;
`,

  routeFile: `const express = require('express');
const router = express.Router();
const <%= controllerName %>Controller = require('../controllers/<%= controllerName %>Controller');
<% endpoints.forEach(ep => { %>
router.<%= ep.method.toLowerCase() %>('<%= ep.subPath %>', <%= controllerName %>Controller.<%= ep.handlerName %>);<% }) %>

module.exports = router;
`,

  controllerFile: `<% endpoints.forEach(ep => { %>
// <%= ep.method %> <%= ep.fullPath %>
exports.<%= ep.handlerName %> = (req, res) => {
  // TODO: implement logic
  res.json(<%-  JSON.stringify(buildSampleResponse(ep.responseSchema), null, 2) %>);
};
<% }) %>
`,
  readme: `# <%= projectName %>

Generated by **API Generator** — Node.js <%= version === 'express5' ? 'Express 5.x' : 'Express 4.x' %>.

## Getting Started

\`\`\`bash
npm install
npm start
\`\`\`

## Requirements

- Node.js <%= version === 'express5' ? 'v18+' : 'v14+' %>

## Endpoints

<% apis.forEach(api => { %>
### <%= api.method %> \`<%= api.path %>\`
<% if (api.description) { %>> <%= api.description %>
<% } %>
**Request Schema:** \`\`\`json
<%- JSON.stringify(api.requestSchema, null, 2) %>
\`\`\`

**Response Schema:** \`\`\`json
<%- JSON.stringify(api.responseSchema, null, 2) %>
\`\`\`
<% }) %>
`
};

// ─── Version-specific package.json configs ─────────────────────────────────────

const NODE_VERSION_CONFIG = {
  express4: {
    expressVersion: '^4.18.2',
    nodeEngine: '>=14.0.0',
    note: 'Express 4.x — widely supported, stable'
  },
  express5: {
    expressVersion: '^5.0.0',
    nodeEngine: '>=18.0.0',
    note: 'Express 5.x — async error auto-forwarding'
  }
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

function buildSampleResponse(schema) {
  if (!schema || typeof schema !== 'object') return {};
  const result = {};
  for (const [key, val] of Object.entries(schema)) {
    if (typeof val === 'object' && !Array.isArray(val)) {
      result[key] = buildSampleResponse(val);
    } else {
      switch (val) {
        case 'string':  result[key] = 'example'; break;
        case 'int':
        case 'number':  result[key] = 0; break;
        case 'boolean': result[key] = true; break;
        case 'array':   result[key] = []; break;
        default:        result[key] = null;
      }
    }
  }
  return result;
}

function groupByResource(apis) {
  const groups = {};
  for (const api of apis) {
    const parts = api.path.replace(/^\//, '').split('/');
    const resource = parts[0] || 'index';
    if (!groups[resource]) groups[resource] = [];
    groups[resource].push(api);
  }
  return groups;
}

function toHandlerName(method, path) {
  const parts = path.replace(/^\//, '').split('/').map(p =>
    p.startsWith(':') ? 'By' + p.slice(1).charAt(0).toUpperCase() + p.slice(2) : p
  );
  const suffix = parts.slice(1).map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');
  return method.toLowerCase() + suffix;
}

// ─── Node.js File Builder ─────────────────────────────────────────────────────

function buildNodeFiles(apis, projectName, version = 'express4') {
  const files = {};
  const groups = groupByResource(apis);
  const cfg = NODE_VERSION_CONFIG[version] || NODE_VERSION_CONFIG.express4;

  const routeImports = Object.keys(groups).map(r =>
    `app.use('/${r}', require('./routes/${r}Route'));`
  ).join('\n');

  files['app.js'] = ejs.render(TEMPLATES.appJs, { projectName, routes: routeImports });

  // Version-specific package.json
  files['package.json'] = JSON.stringify({
    name: projectName,
    version: '1.0.0',
    description: `Generated by API Generator — ${cfg.note}`,
    main: 'app.js',
    engines: { node: cfg.nodeEngine },
    scripts: { start: 'node app.js', dev: 'nodemon app.js' },
    dependencies: { express: cfg.expressVersion },
    devDependencies: { nodemon: '^3.0.2' }
  }, null, 2);

  files['README.md'] = ejs.render(TEMPLATES.readme, { projectName, apis, version });

  for (const [resource, endpoints] of Object.entries(groups)) {
    const enriched = endpoints.map(ep => {
      const subPath = ep.path.replace(new RegExp(`^/?${resource}`), '') || '/';
      return {
        ...ep,
        subPath: subPath || '/',
        fullPath: ep.path,
        handlerName: toHandlerName(ep.method, ep.path)
      };
    });

    files[`routes/${resource}Route.js`] = ejs.render(TEMPLATES.routeFile, {
      controllerName: resource,
      endpoints: enriched
    });

    files[`controllers/${resource}Controller.js`] = ejs.render(TEMPLATES.controllerFile, {
      endpoints: enriched,
      buildSampleResponse
    });

    const modelContent = endpoints.map(ep =>
      `// ${ep.method} ${ep.path}\n// Request: ${JSON.stringify(ep.requestSchema, null, 2)}\n// Response: ${JSON.stringify(ep.responseSchema, null, 2)}`
    ).join('\n\n');
    files[`models/${resource}Model.js`] = `// Model: ${resource}\n\n${modelContent}\n`;
  }

  return files;
}

// ─── Dispatch by language + version ───────────────────────────────────────────

function buildFiles(apis, projectName, language, version) {
  switch (language) {
    case 'python': return buildPythonFiles(apis, projectName, version);
    case 'csharp': return buildCsharpFiles(apis, projectName, version);
    case 'java':   return buildJavaFiles(apis, projectName, version);
    default:       return buildNodeFiles(apis, projectName, version);
  }
}

// ─── Write to disk ────────────────────────────────────────────────────────────

async function generateProject({ apis, projectName, language, version, outputDir }) {
  const files = buildFiles(apis, projectName, language, version);
  for (const [filePath, content] of Object.entries(files)) {
    const fullPath = path.join(outputDir, filePath);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, content, 'utf-8');
  }
  return outputDir;
}

// ─── Preview (no disk write) ──────────────────────────────────────────────────

async function generatePreview({ apis, projectName, language, version }) {
  return buildFiles(apis, projectName, language, version);
}

module.exports = { generateProject, generatePreview };
